### PR TITLE
Template and search improvements

### PR DESCRIPTION
**Pull request by bianchimro**
Hi @meanme, I found your improvements and I'd like to merge them in the main repo, they are all making sense to me.

I'd like to merge them as soon as possible, as I am beginning to work on #1, 
but will soon be addressing #10 that would surely make your fork diverge a bit from my repo.
Is it ok for you? Want to create PR(s) yourself?

Best regards
Mauro

### CODE REVIEW

**Comment by meanme** [comment]
Awesome! Absolutely, please go ahead and merge.
I didn't get a chance to create a demo page to show my changes, please let me know if something is not clear. Thank you for the great component.

**Comment by bianchimro** [comment]
@meanme just merged
it would be great if you could fork my codepen:
http://codepen.io/bianchimro/pen/epYYQO?editors=101
and add a couple of examples with your additions,
so I can make proper docs on the gh-pages branch

thanks for your work!

**Comment by meanme** [comment]
http://codepen.io/meanme/pen/ONmGzW

Search callbacks are meant to be used with an API endpoint, sending no results will show the "not found" element

**Comment by bianchimro** [comment]
thanks a lot for the codepen, I'll integrate examples and docs ASAP

**Pull request merged**
