### PR TITLE
Multiple Checkbox Working

### PR DESCRIPTION
**Pull request by jtushar53**
Will create codepen demo if needed.

``
<label class="item item-input item-select">
          <div class="input-label">
           What to notfiy ?
          </div>
          <button style="visibility: hidden;" modal-select ng-model="SelectedStatus" multiple="true" selected-values="location.selectedvalues" options="categoryList" use-collection-repeat="false" has-search="true" modal-title="Select Category " option-getter="getOption(option)" header-footer-class="bar-positive">
            <div class="option">
               {{option.categoryname}}
            </div>
            <select disabled="true" style="visibility: visible;">
              <option>{{SelectedStatus || 'Select Category' }} </option>
            </select>
          </button>
        </label>
``

### CODE REVIEW

**Comment by bianchimro** [comment]
Hi @jtushar53,
thanks a lot for your work! This is a feature I'd really like to have.

A codepen would be great, so I can quickly take a look at the result, if you make one that would be great
(you can just fork mine and move references to your fork).

Anyway, I noticed you worked directly on the "dist" folder ... this is not acceptable as it would break my current development workflow, which is based on working on the "src" folder, keeping templates in separate html files and using a `gulp` task to generate the "dist" folder and "embed" templates into javascript objects.   

This was my fault, as the development process is not documented at all.
Let me know If you need more help about this.

I am also thinking about changing a bit the interface after implementing this feature as, in my opinion, it is crucial that the user can see quickly what is already selected,  specially when it is possible to select multiple options  (in case of a single option, seeing a selected item is enough, but if you have more you should scroll all the list to see what is selected.
Anyway, we'll take this into account after enabling multiple choices.

Best regards
Mauro

**Comment by jtushar53** [comment]
Hi @bianchimro , 
I am a bit newbie to node js, angularjs and above is my first commit on github.com so in excitement forgot the folder name  :grimacing:

Please review and change as you like.

Here is the demo
http://codepen.io/jtushar53/pen/yeqRNM

Also i was trying to get a workaround for Reset for multiple items which is not working at the moment.

One more thing thank you for the great plugin :beers:

**Comment by mikehenken** [comment]
+1

**Comment by icaliman** [comment]
+1

**Comment by bianchimro** [comment]
hi @jtushar53 ,
sorry but I ended up fixing this in another way.
(it's not really finished but multiple options should be quite usable on master branch now, even if not documented).
Thanks a lot for your work, stay tuned for the next updates that should resolve all issues related to selecting multiple options.

**Pull request closed without merging**
